# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdf8fde6a39970e423fedcd839296abe6a1eef8ff721f43a87fee32f7eb800866d021b236240694278201d75ca736044d23a01f45c706e1e6e08eba70f987689

test:
  secret_key_base: 95e32f5359f10f1de6108d27c716bf04a188e94fc5a37cede04aa24589d84631e02debf6e0bab36a4fce28f86656f5c594e171ded686fe4286348d2f8ed59b8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
